# Generated by Django 5.1.6 on 2025-02-19 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_author_alter_post_banner'),
    ]

    operations = [
    ]
